project_id = "pcuizcypuczvqkaectfu"

[functions.ksef-sync]
verify_jwt = false

[functions.ksef-download]
verify_jwt = false

[functions.elevenlabs-token]
verify_jwt = false

[functions.elevenlabs-webhook]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false
